/* This class handles all File-related actions for a database. These tasks
 * include writing tables and databases to files along with reading files for 
 * databases and tables and parsing/returning them as objects. Tables are saved
 * as tab-delimited text files with their names, columns (key column prefixed 
 * with an asterisk), and records. Databases are stored with their name, 
 * relative folder, and any/all table file names. File objects can be 
 * constructed with database file names (without extension) and directories.
 * Constructor arguments are important to set when determining where databases
 * will be saved (can be taken from database objects or set by user). 
 */

import java.util.ArrayList;
import java.util.List;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

class File {
   private static final String UNITDELIM = "\t";
   private static final String RCRDDELIM = "\n";
   private static final String KEYATTRIB = "*";
   private static final String EXTENSION = ".dbf";
   private static final String DEF_FNAME = "untitled";
   private static final String DEF_FPATH = "/databases/";
   private static final String CENCODING = "UTF-8";
   private static final String USER_PATH = System.getProperty("user.dir");

   private String filename;
   private String dirpath;
   private String filepath;
   private int lineCnt = 0;

   File() {
      this.filename = DEF_FNAME + EXTENSION;
      this.dirpath = USER_PATH + DEF_FPATH;
      this.filepath = this.dirpath + this.filename;
   }

   File(String file) {
      this.filename = file + EXTENSION;
      this.dirpath = USER_PATH + DEF_FPATH;
      this.filepath = this.dirpath + this.filename;
   }

   File(String file, String folder) {
      this.filename = file + EXTENSION;
      this.dirpath = USER_PATH + checkFolderFormatting(folder);
      this.filepath = this.dirpath + this.filename;
   }

   String getFileName() {
      return this.filename;
   }
   
   void setFileName(String name) {
      if (!name.endsWith(EXTENSION)) {
         name = name + EXTENSION;
      }
      this.filename = name;
   }

   String getFilePath() {
      return this.filepath;
   }

   /* no validation: to completely validate file paths is a lot of work; 
    * make this the user's responsibility
    */
   void setFilePath(String name) {
      this.filepath = name;
   }

   void writeDatabaseToFiles(Database database) {
      String databaseInfo = writeDatabaseInfoToString(database);
      writeStringToFile(databaseInfo);
      List<String> tableKeys = database.getKeyList();
      for (String entry : tableKeys) {
         File newTableFile = new File(entry, database.getFolder());
         newTableFile.writeTableToFile(database.select(entry));
      }
   }

   void writeTableToFile(Table table) {
      String tableString = writeTableToString(table);
      writeStringToFile(tableString);
   }

   // takes file path from class fields generated by constructor arguments
   Database readDatabaseFiles() throws Exception {
      BufferedReader bReader = new BufferedReader(new FileReader(this.filepath));
      String line;
      Database outputDB = new Database();
      this.lineCnt = 0;
      while ((line = bReader.readLine()) != null) {
         if (this.lineCnt == 0) {
            outputDB.setName(removeExtensionFromString(line));
         } else if (this.lineCnt == 1) {
            outputDB.setFolder(line);
         } else {
            outputDB.add(readFileToTable(this.dirpath + line));
         }
         this.lineCnt++;
      }
      bReader.close();
      return outputDB;
   }

   // takes file path from database file called from readDatabaseFiles()
   Table readFileToTable(String filepath) throws Exception {
      BufferedReader bReader = new BufferedReader(new FileReader(filepath));
      String line;
      String tableName = new String();
      Table outputTable = new Table();
      this.lineCnt = 0;
      while ((line = bReader.readLine()) != null) {
         if (this.lineCnt == 0) {
            tableName = line;
         } else if (this.lineCnt == 1) {
            outputTable = readColumnsToTable(outputTable, line, tableName);
         } else {
            addTableRecords(outputTable, line);
         }
         this.lineCnt++;
      }
      bReader.close();
      return outputTable;
   }

   // --- helper functions ---

   private String removeExtensionFromString(String str) {
      if (str != null && str.contains(".")) {
         return str.substring(0, str.lastIndexOf('.'));
      }
      return str;
   }

   private void writeStringToFile(String input) {
      Path path = Paths.get(this.dirpath);
      if (!Files.exists(path)) {
         try {
            Files.createDirectories(path); 
         } catch (IOException e) {
            e.printStackTrace(); 
         }
      }
      try {
         Files.write(Paths.get(this.filepath), input.getBytes(CENCODING)); 
      } catch (IOException e) {
         e.printStackTrace(); 
      }
   }

   private String checkFolderFormatting(String folder) {
      if (!folder.startsWith("/")) {
         folder = "/" + folder;
      }
      if (!folder.endsWith("/")) {
         folder = folder + "/";
      }
      return folder;
   }

   // --- table handling ---

   private String writeTableToString(Table table) {
      StringBuilder output = new StringBuilder();
      output.append(table.getName() + RCRDDELIM);
      appendTableColumns(table, output);
      appendTableRecords(table, output);
      return output.toString();
   }

   private void appendTableColumns(Table table, StringBuilder output) {
      int colsz = table.getColumnSize();
      int keyColumn = table.getKeyColumn();
      for (int i = 0; i < colsz; i++) {
         if (i == keyColumn) {
               output.append(KEYATTRIB);
         }
         output.append(table.getColumnName(i));
         if (i < colsz - 1) {
            output.append(UNITDELIM);
         }
      }
      output.append(RCRDDELIM);
   }

   private void appendTableRecords(Table table, StringBuilder output) {
      int colsz = table.getColumnSize();
      List<String> recordKeys = table.getKeyList();
      for (String entry : recordKeys) {
         for (int i = 0; i < colsz; i++) {
            output.append(table.select(entry).getField(i));
            if (i < colsz - 1) {
               output.append(UNITDELIM);
            }
         }
         output.append(RCRDDELIM);
      }
   }

   private Table readColumnsToTable(Table outputTable, String line, String tableName) {
      String[] headers = line.split(UNITDELIM);
      ColumnID[] columns = new ColumnID[headers.length];
      for (int i = 0; i < headers.length; i++) {
         if (headers[i].startsWith("*")) {
            columns[i] = new ColumnID(headers[i].replace(KEYATTRIB, ""), true);
         } else {
            columns[i] = new ColumnID(headers[i], false);
         }
      }
      return new Table(tableName, columns);
   }

   private void addTableRecords(Table outputTable, String line) {
      Record newRecord = new Record();
      String[] fields = line.split(UNITDELIM);
      for (String entry : fields) {
         newRecord.add(entry);
      }
      outputTable.add(newRecord);
   }

   // --- database handling ---
   
   private String writeDatabaseInfoToString(Database database) {
      StringBuilder output = new StringBuilder();
      output.append(database.getName() + EXTENSION + RCRDDELIM);
      output.append(checkFolderFormatting(database.getFolder()) + RCRDDELIM);
      appendDatabaseTables(database, output);
      return output.toString();
   }

   private void appendDatabaseTables(Database database, StringBuilder output) {
      List<String> tableKeys = database.getKeyList();
      for (String entry : tableKeys) {
         output.append(entry + EXTENSION + RCRDDELIM);
      }
   }

   // --- testing ---

   private void testTableFileCreation() {
      // make file objects
      File test0 = new File();
      assert(test0.getFileName().equals("untitled" + EXTENSION));
      String testStr = "test";
      File testFile = new File(testStr);
      assert(testFile.getFileName().equals(testStr + EXTENSION));
      // make tables
      Table testTable = new Table(testStr);
      testTable.setColumnIDs(
         new ColumnID("1", true), 
         new ColumnID("2", false), 
         new ColumnID("3")
      );
      Record testR1 = new Record("a", "b", "c");
      testTable.add(testR1);
      Record testR2 = new Record("x", "y", "z");
      testTable.add(testR2);
      String testOutputStr = testFile.writeTableToString(testTable);
      assert(testOutputStr.equals(
         testStr + RCRDDELIM +
         KEYATTRIB + "1" + UNITDELIM + "2" + UNITDELIM + "3" + RCRDDELIM +
         "a" + UNITDELIM + "b" + UNITDELIM + "c" + RCRDDELIM +
         "x" + UNITDELIM + "y" + UNITDELIM + "z" + RCRDDELIM
      ));
      testFile.writeStringToFile(testOutputStr);
   }

   private void testTableFileParsing() {
      String testStr = "test";
      File testFile = new File(testStr);
      Table testOut = new Table();
      boolean caught = false;
      try { testOut = testFile.readFileToTable(this.dirpath + testStr + EXTENSION); }
      catch (Exception e) { caught = true; }
      assert(caught == false);
      assert(testFile.getFileName().equals(testStr + EXTENSION));
      String testInputFile = testFile.writeTableToString(testOut);
      assert(testInputFile.equals(
         testStr + RCRDDELIM +
         KEYATTRIB + "1" + UNITDELIM + "2" + UNITDELIM + "3" + RCRDDELIM +
         "a" + UNITDELIM + "b" + UNITDELIM + "c" + RCRDDELIM +
         "x" + UNITDELIM + "y" + UNITDELIM + "z" + RCRDDELIM)
      );
   }

   private void testDatabaseFileCreation() {
      // create database
      Database testDB = new Database();   
      String testNameDB = "test_database";
      testDB.setName(testNameDB);
      String testFolderDB = "test_folder";
      testDB.setFolder(testFolderDB);
      // create table1
      String testNameT1 = "test_table1";
      Table testTable1 = new Table(
         testNameT1, 
         new ColumnID("key", true), 
         new ColumnID("2", false), 
         new ColumnID("3")
      );
      Record testT1R1 = new Record("key1", "1", "1");
      Record testT1R2 = new Record("key2", "1", "2");
      testTable1.add(testT1R1);
      testTable1.add(testT1R2);
      // create table2
      String testNameT2 = "test_table2";
      Table testTable2 = new Table(
         testNameT2, 
         new ColumnID("key", true), 
         new ColumnID("2", false), 
         new ColumnID("3")
      );
      Record testT2R1 = new Record("key1", "1", "1");
      Record testT2R2 = new Record("key2", "1", "2");
      testTable2.add(testT2R1);
      testTable2.add(testT2R2);
      // add tables to database
      testDB.add(testTable1);
      testDB.add(testTable2);
      // create File object
      File testDBFile = new File(testNameDB, testFolderDB);
      String testOutputDBStr = testDBFile.writeDatabaseInfoToString(testDB);
      assert(testOutputDBStr.equals(
         testNameDB + EXTENSION + RCRDDELIM +
         checkFolderFormatting(testFolderDB) + RCRDDELIM +
         testNameT1 + EXTENSION + RCRDDELIM +
         testNameT2 + EXTENSION + RCRDDELIM)
      );
      testDBFile.writeDatabaseToFiles(testDB);
   }

   private void testDatabaseFileParsing() {
      // create database
      Database testDB = new Database();   
      String testNameDB = "test_database";
      testDB.setName(testNameDB);
      String testFolderDB = "test_folder";
      testDB.setFolder(testFolderDB);
      // create table1
      String testNameT1 = "test_table1";
      Table testTable1 = new Table(
         testNameT1, 
         new ColumnID("key", true), 
         new ColumnID("2", false), 
         new ColumnID("3")
      );
      Record testT1R1 = new Record("key1", "1", "1");
      Record testT1R2 = new Record("key2", "1", "2");
      testTable1.add(testT1R1);
      testTable1.add(testT1R2);
      // create table2
      String testNameT2 = "test_table2";
      Table testTable2 = new Table(
         testNameT2, 
         new ColumnID("key", true), 
         new ColumnID("2", false), 
         new ColumnID("3")
      );
      Record testT2R1 = new Record("key1", "1", "1");
      Record testT2R2 = new Record("key2", "1", "2");
      testTable2.add(testT2R1);
      testTable2.add(testT2R2);
      // add tables to database
      testDB.add(testTable1);
      testDB.add(testTable2);
      // create File object
      File testDBFile = new File(testNameDB, testFolderDB);
      Database testOutDB = new Database(testNameDB, testFolderDB);
      boolean caught = false;
      try { testOutDB = testDBFile.readDatabaseFiles(); }
      catch (Exception e) { caught = true; e.printStackTrace(); }
      assert(caught == false);
      // check new database object
      assert(testOutDB.getName().equals(testNameDB));
      assert(testOutDB.getFolder().equals(checkFolderFormatting(testFolderDB)));
      assert(testOutDB.select(testNameT1).select("key1").getField(1).equals("1"));
      assert(testOutDB.select(testNameT2).select("key2").getField(2).equals("2"));
   }

   private void runTests() {
      testTableFileCreation();
      testTableFileParsing();
      testDatabaseFileCreation();
      testDatabaseFileParsing();
   }

   public static void main(String[] args) {
      File program = new File();
      program.runTests();
   }
}
